# Generated by Django 5.1.1 on 2024-10-25 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Technology Name')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Technology Type')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('link', models.URLField(help_text='Enter a link to the project or repository.')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the project.', null=True, upload_to='images/', verbose_name='Project Image')),
                ('technologies', models.ManyToManyField(related_name='projects', to='projects.technology', verbose_name='Technologies Used')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='technology',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='projects.technologytype', verbose_name='Type'),
        ),
    ]
